name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify on success
        if: success()
        run: echo "your push has been successfully accepted!" | send-notification-command
